### ISSUE TITLE
intellij support

### ISSUE THREAD

**Issue by fommil** [fommil/stalactite#1]
https://blog.jetbrains.com/scala/2015/10/14/intellij-api-to-build-scala-macros-support/

**Comment by fommil** [comment]
hi @mutcianm I'd like to write IntelliJ plugin support for this macro. It should be trivial, it's just adding a single implicit val into the companion, and the right hand side can be null to make everything faster. Could you please help me do that? Does it get released separately or does it need to be part of the core scala plugin?

**Comment by jastice** [comment]
You could release the support either as a separate plugin which depends on the Scala plugin, or implement it directly in the Scala plugin and open a PR. In that case it would become available with the next nightly build. That would be the easier route, assuming we want to accept it ;)

As to how exactly to implement it, @mutcianm can probably help you better.

Since the links on the blog post are dead/outdated, here's current versions:
* https://github.com/JetBrains/intellij-scala/blob/idea172.x/src/org/jetbrains/plugins/scala/lang/psi/impl/toplevel/typedef/MonocleInjector.scala
* https://github.com/JetBrains/intellij-scala/blob/idea172.x/src/org/jetbrains/plugins/scala/lang/psi/impl/toplevel/typedef/simulacrum/SimulacrumInjection.scala

**Comment by fommil** [comment]
@Alefas could you please help with this? This macro is much simpler than simulacrum or monocle. I am checking out the repo and will try to do something, but I may need help running and creating tests.

**Comment by fommil** [comment]
check out my branch and `sbt packagePluginCommunityZip` then install the resulting `out/*.zip` in IntelliJ. I have a branch with a backport to 2016.3.6

**Comment by fommil** [comment]
plugin zip available at https://github.com/fommil/stalactite/releases/tag/v0.0.2
